

stages:
  - lint
  - build
  - deploy

lint-test:
  image: node:18.16.0-alpine
  stage: lint

  script:
    - |
      npm install eslint \
      eslint-config-next \
      eslint-config-prettier \
      eslint-config-standard-with-typescript \
      eslint-plugin-import \
      eslint-plugin-jsx-a11y \
      eslint-plugin-prettier \
      eslint-plugin-react \
      eslint-plugin-simple-import-sort \
      eslint-plugin-unused-imports
    # - npm i
    - npm run lint
  except:
    - development

